# Generated by Django 5.0.7 on 2024-08-02 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_number',
        ),
    ]
