# Generated by Django 5.0.7 on 2024-08-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtype',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bloodtype',
            name='code',
            field=models.CharField(default='A', max_length=100, unique=True),
        ),
    ]
