# Generated by Django 5.0.7 on 2024-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0002_remove_bloodtype_quantity_bloodtype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='code',
            field=models.CharField(default='A', max_length=100, unique=True),
        ),
    ]
