# Generated by Django 5.0.7 on 2024-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0003_bloodbank_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='date',
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='code',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='Expiration_date',
            field=models.DateTimeField(null=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bloodtype',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='code',
            field=models.CharField(default='A', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
    ]
