# Generated by Django 5.0.7 on 2024-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0004_remove_blooddonation_date_bloodbag_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='Expiration_date',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
