# Generated by Django 5.0.7 on 2024-09-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0005_alter_blooddonation_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='quantity',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_a_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_a_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_ab_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_ab_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_b_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_b_plus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_o_minus',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='quantity_o_plus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
