# Generated by Django 5.0.7 on 2024-09-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0008_alter_bloodbank_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodbank',
            options={},
        ),
    ]
