# Generated by Django 5.0.7 on 2024-09-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0010_alter_bloodbag_quantity_alter_blooddonation_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodtype',
            name='quantity',
        ),
    ]
