# Generated by Django 5.0.7 on 2024-09-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0012_bloodbank_name_alter_bloodbag_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
