# Generated by Django 5.0.7 on 2024-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0013_alter_bloodbank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
