# Generated by Django 5.0.7 on 2024-09-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0015_remove_command_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='sequence_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
