# Generated by Django 5.0.7 on 2024-10-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0018_users_password_alter_donor_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
