# Generated by Django 5.0.7 on 2025-10-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0019_hospital_name_alter_command_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
