# Generated by Django 5.0.7 on 2025-10-03 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0020_alter_donor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='date',
        ),
    ]
