# Generated by Django 5.0.7 on 2025-10-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0021_remove_donor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
