# Generated by Django 5.0.7 on 2025-10-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mblood', '0022_donor_last_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
